### ISSUE TITLE
Create docker compose

### ISSUE THREAD

**Issue by martinbalucha** [eKultura/research.digitalni-muzeum.cz#20]
With coming dependencies, it would be more convenient to work with Docker Compose than with just a plain Dockerfile. For now, the docker compose should contain one service with a volume that serves as a storage for PDF files.

**Comment by KuceraMar** [comment]
## List of existing Dockerfiles

- [Frontend Dockerfile](https://github.com/eKultura/research.digitalni-muzeum.cz/blob/main/frontend/Dockerfile)
- [Backend Dockerfile](https://github.com/eKultura/research.digitalni-muzeum.cz/blob/main/backend/src/EntityExtractor.Web/Dockerfile)

## docker-compose.yml 
```
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
    networks:
      - research_app

  backend:
    build:
      context: ./backend/src/EntityExtractor.Web
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./pdf_data:/app/pdf_data
    networks:
      - research_app

networks:
  research_app:
    driver: bridge
```


## .ENV
```
# Ports
FRONTEND_PORT=3022
BACKEND_PORT=8022
```
